---
logs:
  level: DEBUG
  token: ~
fastqc:
  appId: urrutia-fastqc-0.11.9
  name: fastqc_test
  archive: true
  archivePath: ""
  archiveSystem: ""
  inputs:
    fastq: ""
  notifications:
    -
      event: FINISHED
      url: your@email.com
